SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS app_meta (
        key TEXT PRIMARY KEY,
        value TEXT,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS users (
        user_id TEXT PRIMARY KEY,
        balance BIGINT DEFAULT 2500,
        last_daily TIMESTAMPTZ,
        last_work TIMESTAMPTZ,
        last_crime TIMESTAMPTZ,
        daily_streak INTEGER DEFAULT 0,
        total_earned BIGINT DEFAULT 2500,
        total_donated BIGINT DEFAULT 0,
        lottery_week TEXT,
        lottery_tickets INTEGER DEFAULT 0,
        lottery_wins INTEGER DEFAULT 0,
        total_lottery_won BIGINT DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL REFERENCES users(user_id),
        item_name TEXT NOT NULL,
        item_data TEXT,
        acquired_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_levels (
        user_id TEXT,
        guild_id TEXT,
        xp INTEGER DEFAULT 0,
        level INTEGER DEFAULT 1,
        reputation INTEGER DEFAULT 0,
        messages_sent INTEGER DEFAULT 0,
        daily_streak INTEGER DEFAULT 0,
        last_daily TIMESTAMPTZ,
        last_message_at DOUBLE PRECISION DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (user_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_reputation (
        user_id TEXT,
        guild_id TEXT,
        reputation INTEGER DEFAULT 0,
        PRIMARY KEY (user_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS welcome_config (
        guild_id TEXT PRIMARY KEY,
        channel_id TEXT,
        message TEXT,
        config_json TEXT,
        enabled INTEGER DEFAULT 1,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS reminders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        channel_id TEXT NOT NULL,
        message TEXT NOT NULL,
        remind_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        recurring INTEGER DEFAULT 0,
        interval_seconds INTEGER DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS scheduled_announcements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        channel_id TEXT NOT NULL,
        message TEXT,
        scheduled_for TIMESTAMPTZ NOT NULL,
        created_by TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        embed_json TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tickets (
        ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        channel_id TEXT UNIQUE NOT NULL,
        user_id TEXT NOT NULL,
        status TEXT DEFAULT 'open',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        closed_at TIMESTAMPTZ,
        closed_by TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS transactions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        from_user_id TEXT,
        to_user_id TEXT,
        amount BIGINT NOT NULL,
        transaction_type TEXT NOT NULL,
        description TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS moderation_logs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        moderator_id TEXT NOT NULL,
        action TEXT NOT NULL,
        reason TEXT,
        duration INTEGER,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS warnings (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        moderator_id TEXT NOT NULL,
        reason TEXT NOT NULL,
        active INTEGER DEFAULT 1,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS game_stats (
        user_id TEXT NOT NULL,
        game_type TEXT NOT NULL,
        wins INTEGER DEFAULT 0,
        losses INTEGER DEFAULT 0,
        draws INTEGER DEFAULT 0,
        total_games INTEGER DEFAULT 0,
        total_earnings BIGINT DEFAULT 0,
        best_streak INTEGER DEFAULT 0,
        current_streak INTEGER DEFAULT 0,
        last_played TIMESTAMPTZ,
        PRIMARY KEY (user_id, game_type)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tournaments (
        tournament_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        game_type TEXT NOT NULL,
        creator_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        name TEXT NOT NULL,
        start_time TIMESTAMPTZ,
        end_time TIMESTAMPTZ,
        prize_pool BIGINT DEFAULT 0,
        status TEXT DEFAULT 'open',
        max_players INTEGER DEFAULT 8,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tournament_participants (
        tournament_id BIGINT REFERENCES tournaments(tournament_id),
        user_id TEXT NOT NULL,
        score INTEGER DEFAULT 0,
        rank INTEGER,
        joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_badges (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        badge_id TEXT NOT NULL,
        badge_name TEXT NOT NULL,
        badge_emoji TEXT,
        badge_description TEXT,
        earned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (user_id, guild_id, badge_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_profiles (
        user_id TEXT,
        guild_id TEXT,
        bio TEXT,
        color TEXT DEFAULT '#5865F2',
        banner_url TEXT,
        favorite_game TEXT,
        birthday DATE,
        pronouns TEXT,
        custom_field_1_name TEXT,
        custom_field_1_value TEXT,
        custom_field_2_name TEXT,
        custom_field_2_value TEXT,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (user_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS marriages (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        user1_id TEXT NOT NULL,
        user2_id TEXT NOT NULL,
        married_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        ring_tier INTEGER DEFAULT 1,
        anniversary_count INTEGER DEFAULT 0,
        status TEXT DEFAULT 'active',
        UNIQUE (guild_id, user1_id, user2_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS activity_history (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        activity_type TEXT NOT NULL,
        activity_data TEXT,
        timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS friendships (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        friend_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        accepted_at TIMESTAMPTZ,
        UNIQUE (user_id, friend_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS message_stats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        date DATE NOT NULL,
        message_count INTEGER DEFAULT 0,
        xp_gained INTEGER DEFAULT 0,
        UNIQUE (user_id, guild_id, date)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_streaks (
        user_id TEXT,
        guild_id TEXT,
        streak_type TEXT,
        current_streak INTEGER DEFAULT 0,
        best_streak INTEGER DEFAULT 0,
        last_activity TIMESTAMPTZ,
        total_rewards BIGINT DEFAULT 0,
        PRIMARY KEY (user_id, guild_id, streak_type)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS custom_roles (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        role_id TEXT UNIQUE NOT NULL,
        role_name TEXT NOT NULL,
        role_color TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMPTZ,
        UNIQUE (user_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS trades (
        trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        sender_id TEXT NOT NULL,
        receiver_id TEXT NOT NULL,
        sender_offer_coins BIGINT DEFAULT 0,
        sender_offer_items TEXT,
        receiver_offer_coins BIGINT DEFAULT 0,
        receiver_offer_items TEXT,
        status TEXT DEFAULT 'pending',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        completed_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS achievements (
        achievement_id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        emoji TEXT,
        reward_coins BIGINT DEFAULT 0,
        reward_badge TEXT,
        requirement_type TEXT NOT NULL,
        requirement_value INTEGER,
        tier TEXT DEFAULT 'bronze',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_achievements (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        achievement_id TEXT NOT NULL REFERENCES achievements(achievement_id),
        unlocked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        claimed INTEGER DEFAULT 0,
        UNIQUE (user_id, guild_id, achievement_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auctions (
        auction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        seller_id TEXT NOT NULL,
        item_name TEXT NOT NULL,
        item_description TEXT,
        item_emoji TEXT,
        item_rarity TEXT DEFAULT 'common',
        starting_bid BIGINT NOT NULL,
        current_bid BIGINT,
        current_bidder_id TEXT,
        buyout_price BIGINT,
        status TEXT DEFAULT 'active',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        ends_at TIMESTAMPTZ NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS auction_bids (
        bid_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        auction_id BIGINT NOT NULL REFERENCES auctions(auction_id),
        bidder_id TEXT NOT NULL,
        bid_amount BIGINT NOT NULL,
        bid_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS active_events (
        event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        event_type TEXT NOT NULL,
        event_name TEXT NOT NULL,
        multiplier DOUBLE PRECISION DEFAULT 1.0,
        bonus_coins BIGINT DEFAULT 0,
        description TEXT,
        started_by TEXT,
        started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        ends_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS inventory_items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        item_id TEXT NOT NULL,
        item_name TEXT NOT NULL,
        item_type TEXT NOT NULL,
        item_rarity TEXT DEFAULT 'common',
        item_data TEXT,
        quantity INTEGER DEFAULT 1,
        tradeable INTEGER DEFAULT 1,
        acquired_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (user_id, guild_id, item_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS moderation_strikes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        moderator_id TEXT NOT NULL,
        reason TEXT NOT NULL,
        strike_count INTEGER DEFAULT 1,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        expires_at TIMESTAMPTZ,
        is_active INTEGER DEFAULT 1
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS role_backups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        role_ids TEXT NOT NULL,
        backed_up_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        reason TEXT DEFAULT 'ban'
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS suggestions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        user_id TEXT NOT NULL,
        channel_id TEXT NOT NULL,
        message_id TEXT UNIQUE NOT NULL,
        suggestion TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        upvotes INTEGER DEFAULT 0,
        downvotes INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        reviewed_by TEXT,
        reviewed_at TIMESTAMPTZ,
        review_note TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS suggestion_votes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        suggestion_id BIGINT NOT NULL REFERENCES suggestions(id),
        user_id TEXT NOT NULL,
        vote_type TEXT NOT NULL,
        voted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (suggestion_id, user_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS giveaways (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        channel_id TEXT NOT NULL,
        message_id TEXT UNIQUE NOT NULL,
        host_id TEXT NOT NULL,
        prize TEXT NOT NULL,
        winners_count INTEGER DEFAULT 1,
        requirements TEXT,
        entries TEXT,
        ends_at TIMESTAMPTZ NOT NULL,
        status TEXT DEFAULT 'active',
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        ended_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS giveaway_entries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        giveaway_id BIGINT NOT NULL REFERENCES giveaways(id),
        user_id TEXT NOT NULL,
        entries INTEGER DEFAULT 1,
        joined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (giveaway_id, user_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS personal_notes (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        title TEXT NOT NULL,
        content TEXT NOT NULL,
        tags TEXT,
        pinned INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS voice_stats (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        guild_id TEXT NOT NULL,
        channel_id TEXT NOT NULL,
        join_time TIMESTAMPTZ NOT NULL,
        leave_time TIMESTAMPTZ,
        duration INTEGER DEFAULT 0,
        date DATE NOT NULL,
        UNIQUE (user_id, guild_id, join_time)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS voice_totals (
        user_id TEXT,
        guild_id TEXT,
        total_time BIGINT DEFAULT 0,
        sessions_count INTEGER DEFAULT 0,
        last_session TIMESTAMPTZ,
        PRIMARY KEY (user_id, guild_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS starboard (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        guild_id TEXT NOT NULL,
        message_id TEXT UNIQUE NOT NULL,
        channel_id TEXT NOT NULL,
        author_id TEXT NOT NULL,
        starboard_message_id TEXT,
        star_count INTEGER DEFAULT 0,
        content TEXT,
        attachment_urls TEXT,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        starred_at TIMESTAMPTZ
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS starboard_stars (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        starboard_id BIGINT NOT NULL REFERENCES starboard(id),
        user_id TEXT NOT NULL,
        starred_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        UNIQUE (starboard_id, user_id)
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS starboard_config (
        guild_id TEXT PRIMARY KEY,
        channel_id TEXT,
        star_threshold INTEGER DEFAULT 3,
        emoji TEXT DEFAULT '⭐',
        enabled INTEGER DEFAULT 1,
        self_star INTEGER DEFAULT 0,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS afk_status (
        user_id TEXT,
        guild_id TEXT,
        reason TEXT,
        set_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        PRIMARY KEY (user_id, guild_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_user_items_user ON user_items(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_transactions_from ON transactions(from_user_id)",
    "CREATE INDEX IF NOT EXISTS idx_transactions_to ON transactions(to_user_id)",
    "CREATE INDEX IF NOT EXISTS idx_mod_logs_guild ON moderation_logs(guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_warnings_user ON warnings(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_game_stats_user ON game_stats(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_game_stats_type ON game_stats(game_type)",
    "CREATE INDEX IF NOT EXISTS idx_tournaments_guild ON tournaments(guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_badges_user ON user_badges(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_activity_user ON activity_history(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_marriages_users ON marriages(user1_id, user2_id)",
    "CREATE INDEX IF NOT EXISTS idx_custom_roles_user ON custom_roles(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_auctions_status ON auctions(status, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_inventory_user ON inventory_items(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_events_active ON active_events(guild_id, ends_at)",
    "CREATE INDEX IF NOT EXISTS idx_strikes_user ON moderation_strikes(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_strikes_active ON moderation_strikes(is_active, expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_role_backups_user ON role_backups(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_suggestions_guild ON suggestions(guild_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_suggestions_user ON suggestions(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_giveaways_status ON giveaways(status, ends_at)",
    "CREATE INDEX IF NOT EXISTS idx_giveaways_guild ON giveaways(guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_notes_user ON personal_notes(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_voice_user ON voice_stats(user_id, guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_voice_date ON voice_stats(guild_id, date)",
    "CREATE INDEX IF NOT EXISTS idx_starboard_guild ON starboard(guild_id, star_count)",
    "CREATE INDEX IF NOT EXISTS idx_starboard_msg ON starboard(message_id)",
    "CREATE INDEX IF NOT EXISTS idx_afk_guild ON afk_status(guild_id)",
    "CREATE INDEX IF NOT EXISTS idx_reminders_due ON reminders(remind_at)",
    "CREATE INDEX IF NOT EXISTS idx_reminders_user ON reminders(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_scheduled_announcements_due ON scheduled_announcements(scheduled_for)",
]

ALTER_STATEMENTS = [
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_work TIMESTAMPTZ",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS last_crime TIMESTAMPTZ",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS lottery_week TEXT",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS lottery_tickets INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS lottery_wins INTEGER DEFAULT 0",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS total_lottery_won BIGINT DEFAULT 0",
    "ALTER TABLE user_levels ADD COLUMN IF NOT EXISTS daily_streak INTEGER DEFAULT 0",
    "ALTER TABLE user_levels ADD COLUMN IF NOT EXISTS last_daily TIMESTAMPTZ",
    "ALTER TABLE welcome_config ADD COLUMN IF NOT EXISTS config_json TEXT",
]

MIGRATION_TABLE_ORDER = [
    "users",
    "user_items",
    "user_levels",
    "user_reputation",
    "welcome_config",
    "tickets",
    "transactions",
    "moderation_logs",
    "warnings",
    "game_stats",
    "tournaments",
    "tournament_participants",
    "user_badges",
    "user_profiles",
    "marriages",
    "activity_history",
    "friendships",
    "message_stats",
    "user_streaks",
    "custom_roles",
    "trades",
    "achievements",
    "user_achievements",
    "auctions",
    "auction_bids",
    "active_events",
    "inventory_items",
    "moderation_strikes",
    "role_backups",
    "suggestions",
    "suggestion_votes",
    "giveaways",
    "giveaway_entries",
    "personal_notes",
    "voice_stats",
    "voice_totals",
    "starboard",
    "starboard_stars",
    "starboard_config",
    "afk_status",
]

IDENTITY_COLUMNS = {
    "user_items": "id",
    "tickets": "ticket_id",
    "transactions": "id",
    "moderation_logs": "id",
    "warnings": "id",
    "tournaments": "tournament_id",
    "user_badges": "id",
    "marriages": "id",
    "activity_history": "id",
    "friendships": "id",
    "message_stats": "id",
    "custom_roles": "id",
    "trades": "trade_id",
    "user_achievements": "id",
    "auctions": "auction_id",
    "auction_bids": "bid_id",
    "active_events": "event_id",
    "inventory_items": "id",
    "moderation_strikes": "id",
    "role_backups": "id",
    "suggestions": "id",
    "suggestion_votes": "id",
    "giveaways": "id",
    "giveaway_entries": "id",
    "personal_notes": "id",
    "voice_stats": "id",
    "starboard": "id",
    "starboard_stars": "id",
}